sudo: false
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.8
    packages:
    - clang-11.0
install:
- "[ $CXX = clang++ ] && export CXX=clang++-11.0 || true"
script:
  - cmake .
  - make